# Generated by Django 2.2.7 on 2019-11-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20191113_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
