# Generated by Django 2.2.7 on 2019-11-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_comment_poem_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
