# Generated by Django 2.2.7 on 2019-11-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_auto_20191116_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
