# Generated by Django 2.2.7 on 2019-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_auto_20191117_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
