# Generated by Django 2.2.7 on 2019-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='actual_owner',
            field=models.CharField(default='author', max_length=80),
        ),
    ]
