# Generated by Django 2.2.7 on 2019-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0012_poem_actual_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='detail-view'),
        ),
    ]
