# Generated by Django 2.2.7 on 2019-11-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0013_photo_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date',
        ),
    ]
