# Generated by Django 2.2.7 on 2019-11-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0014_auto_20191125_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created',
        ),
    ]
